### ISSUE TITLE
Brand and mission statement alignment

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/wand#1]
If it _makes_ wizards, shouldn't it be called "Hogwarts", instead of "wand"?

Might leverage more synergy between brand and the core principles.

**Comment by mapsam** [comment]
Isn't this project _a wizard itself_? What/who does a wizard worship?

Since we are talking about ingredients and nodes, it almost seems like Potions ingredients and recipes would be relevant for naming schema.

I'm all for brand synergy :point_right: :tophat:

**Comment by msknee** [comment]
Following this issue has led me to this wikipedia page: https://en.wikipedia.org/wiki/Magocracy

**Comment by daguar** [comment]
I would proffer that if it _makes_ Wizards, then it should follow the [Factory Pattern](https://en.wikipedia.org/wiki/Factory_%28object-oriented_programming%29) and be called a WizardFactory.

**Comment by ErnieAtLYD** [comment]
"Wand: _something something wizards something!_"

That said, I think it should be called _Shirley_. There is no logic or reasoning behind that, I think Shirley is a neat name.

**Comment by mapsam** [comment]
![shirley](https://cloud.githubusercontent.com/assets/1943001/8364060/531f9b26-1b51-11e5-94e0-9ff4faa0e228.gif)

**Comment by msknee** [comment]
Shirley was almost my English name! I protested, so my parents went with the closest alternative, Shelly.
