### ISSUE TITLE
Standardize on Library Pattern

### ISSUE THREAD

**Issue by creade** [codeforamerica/wand#11]
I know we chuckled a little bit about AMD support and all that jazz but I'd like to move to the pattern here: 

http://stackoverflow.com/a/6824210

**Comment by bsmithgall** [comment]
:+1: I think this is the right way to go, would defer to @mapsam though.

A big open question is how to handle multiple files? For example, I image that we will probably have something like `Wand.render` pretty soon.

**Comment by mapsam** [comment]
:+1: nice! I'm totally fine moving into this pattern. I've used both, and I think it really depends on how we envision the plugin architecture being used. Right now using function declarations will do the trick, but eventually we'll need to include `Wand.prototype.FOO = function() { ... }` if we want plugins to hook into the `Wand` functionality. Maybe cross that :bridge_at_night: when we come to it?
