### ISSUE TITLE
Fleshed-out trigger specifications

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/wand#13]
Let's talk about fleshed-out trigger specifications! (Per #6.)

What kinds of trigger specifications should exist? Note that as of right now the code base doesn't have much - here's the `renderTrigger` method, for example: https://github.com/codeforamerica/wand/blob/master/src/js/wand.js#L37-L46

cc: @bengolder @ErnieAtLYD @hamhands @creade @mapsam

**Comment by bsmithgall** [comment]
@ErnieAtLYD when building links, there should be some sort of flags around whether you want to try to get the browser to open in a new tab (`target=_blank`). There might also be some trouble worth thinking about around having "external" (absolute) links vs. relative links.

**Comment by hamhands** [comment]
OMG it's like @bsmithgall is [reading my mind...](https://github.com/codeforamerica/pittsburgh-purchasing-suite/issues/82)

**Comment by bengolder** [comment]
@ErnieAtLYD could you explain a little about the needs in your use case for Miami-Dade? If I understood, there was a need to have a trigger that calls upon external resources, perhaps making an ajax request. Is that correct?

**Comment by ErnieAtLYD** [comment]
That's correct. So for http://codeforamerica.github.io/mdc-step-wizard, we have a text box which takes input. From there, an API is called. If the API returns true it goes down one path, if not it goes down another.

For example, here's a Javascript snippet of an API @phiden used for our Dade wizard:
https://github.com/codeforamerica/mdc-step-wizard/blob/master/app.js#L317-L343

Sophia does a logic check of `if(data.features.length > 0)`. The thought is maybe that if it's `true` it can automatically traverse down a node.

That said, it may be feasible where it doesn't automatically traverse a node just because an API is returned a certain way. Maybe an additional node becomes visible, or something else.

**Comment by bengolder** [comment]
Here are some questions that might help get the discussion going, and some of my initial thoughts. Feel free to edit this comment to add to these.

_What do triggers have in common?_
- some html that takes a user action (text box, button)
- the event that is fired by user input and which initiates the triggered function
- the triggered function, which can simply take you to the appropriate node or can call on external resources.

_What are some of the examples we might want to support?_
- pickOne (a set of singular options, such as yes/no)?
- calling a custom trigger function that does ajax and then links you to the next step (would cover your case)?
- pickMultiple (some combination of options)?
- input data (like text or a number)?

_What are some examples of cases we **don't** want to support?_

_What are some other questions to consider?_
- What about multiple buttons that each do very different things?
- Accounting for different input widgets seems like a rabbit hole, where do we draw the line? 
- How do we allow others to customize their triggers?

**Comment by ErnieAtLYD** [comment]
(Also - I spun off a new page of the wiki to officially list out the specifications: https://github.com/codeforamerica/wand/wiki/Wand-Triggers-Specification - I've added the attributes for type `pickOne`; feel free to add/edit more things with your thoughts.)

**Comment by ErnieAtLYD** [comment]
7/13: 

-We'll be targeting two trigger types:
1. "Pick A Button" that leads to another node on user click
2. "Custom" that has a UI element, is triggered by a user initiated event, can take some action and can easily direct to the appropriate node based on the result of its action.

**Comment by mapsam** [comment]
CUSTOM!

![wand](https://cloud.githubusercontent.com/assets/1943001/8661500/db19ec74-296c-11e5-96f9-5929b65362dd.gif)

**Comment by bsmithgall** [comment]
@ErnieAtLYD is the code that you worked on there checked in somewhere?

**Comment by ErnieAtLYD** [comment]
@bsmithgall: I thought I did, but sadly when I did a `git status` it doesn't look like I have any diff'ed files of the sort. :-/

**Comment by ErnieAtLYD** [comment]
> "Custom" has a UI element, is triggered by a user initiated event, can take some action and can easily direct to the appropriate node based on the result of its action.

Okay, so let's continue this conversation. I went ahead and started a `custom-triggers` branch.

So let's say I have a UI element that is a text box. What's the best way to treat that? Note that I would still have to take action on that text box, call an API, then direct that to a node depending on its result. I submitted a start to where I think this may go.

**Comment by bsmithgall** [comment]
Open question with "custom" triggers -- how do you "direct to the appropriate node based on the result of its action"? Like what is the listener? It feels like the trigger itself should have an argument that is a function that parses the results of whatever the external call is. It would be pretty much impossible to do anything else, right?

**Comment by ErnieAtLYD** [comment]
@bsmithgall: We do recognize `onClick` for `renderTrigger` (https://github.com/codeforamerica/wand/blob/master/src/js/wand.js#L63) so maybe it's a matter of adding other listeners like `onSubmit`? Should that be part of the arguments to pass in along with the parsing function?

**Comment by ErnieAtLYD** [comment]
I'm taking wild stabs at this:

```
{
    "id": "FART",
    "title": "This is a custom trigger",
    "content": "This should be a textbox but what's the best way to show this?",
    "type": "custom",
    "triggers": [
        {
            "description": "Please type your address.",
            "listener": "onSubmit",
            "api": "http://www.x.com/api/",
            "callback": "callback_function"
        }
    ]
}
```

Would a spec like that even work? The caveat to this is that it doesn't give targets for the results of the callback.

cc: @bengolder @hamhands @creade @mapsam @bsmithgall

**Comment by bsmithgall** [comment]
callback should be a function literal.

`callback: callbackFn`

I think that the callback function itself should probably be of a certain form. Like it has to return a target or something like that.

**Comment by mapsam** [comment]
I like the idea of a callback function! Where does the callback function exist?

**Comment by bsmithgall** [comment]
It would have to be external to wand. I don't really know how else this could work.

**Comment by mapsam** [comment]
Potentially a wand plugin!

**Comment by bsmithgall** [comment]
Example pseudo code that (obviously) won't work, but demonstrates the thinking a bit:

In the wand spec:

```
...
"triggers": [
    ...
    "callback": function() {return 1;}
]
...
```

In engine.js:

```
      case 'custom':
        var elem = document.createElement('div');
        elem.innerHTML = triggerHtml;
        var _trigger = document.getElementById('');
        _trigger.onSubmit = function() {
          $('yourThing').success(function(data) {
            wand.engine.renderNode(trigger.callbackFn(data))
          })
        }
```

This will always render node 1.

The big question becomes, if callback is a function literal, how do you handle storage, because then it isn't valid json. Maybe we just need to write a function encoder/decoder that scans the spec and creates references to functions from their names? Does JS support call by name?

**Comment by mapsam** [comment]
:+1: for the callback that way - It seems best to just have the editor generate a function name and have the user write their own outside of the JSON object. If you are writing your own trigger, you likely have some idea of what's going on. What I'm really excited about is the potential have people write custom trigger plugins, like a "geocoder" trigger for instance, that can be used by anyone who includes `wand.geocoder.js` in their page (hint hint, team Miami :wink:)

@ErnieAtLYD you should look at testing with http://yesno.wtf/api for starters - I saw @bsmithgall playing with this and it seemed like a perfect opportunity for testing.

**Comment by ErnieAtLYD** [comment]
@mapsam: [looks around to see if you're referring to anyone else but us]

I can take a stab at it. May need this to be a mob when I get back on Monday since that doesn't sound too trivial.

**Comment by mapsam** [comment]
+1 for mob - I'm mostly talking with the wind and have no idea what type of hole we'd dig during implementation.

**Comment by bsmithgall** [comment]
I have some ideas, what if we did a mob review next week? I think it's
going to be a bit of work that isn't really easily to accomplish in a mob
session.

**Comment by ErnieAtLYD** [comment]
@mapsam: Though that leaves more of a product question: should there be any particular plugin that is not an external trigger plugin?

Since a common interface could be
1. Display a text box
2. Put in a text or numerical value and press enter, submitting the form
3. _VOODOO API MAGIC IS TRIGGERED WHICH REDIRECTS SOMEWHERE_

Maybe we show a text box by using `"type": "textbox"` instead of `"type": "custom"`?

**Comment by mapsam** [comment]
Good question! I don't know if I have an answer. Let's discuss in person and with a whiteboard :pencil2: :white_large_square:

**Comment by ErnieAtLYD** [comment]
Marking this as closed. Right now we'll just have a trigger based on the standard trigger and one based off of apis. If there are other types of triggers we can deal with them on a case-by-case basis.
