### ISSUE TITLE
add a unit test to enforce unique node identifiers

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/wand#20]
We were thinking of writing this test:

```
it('should enforce unique node identifiers', function () {});
```

Should we? Should it?

**Comment by mapsam** [comment]
Should they?

**Comment by ErnieAtLYD** [comment]
I would vote yes. I think @phiden was having some issue on her own unique step wizard with multiple nodes having the same identifiers.

**Comment by bsmithgall** [comment]
Yes absolutely :+1: :100: it wouldn't be an ID if it didn't identify right ;)

**Comment by mapsam** [comment]
Shall thou?

:+1: IDs should always be unique!

**Comment by bsmithgall** [comment]
@ErnieAtLYD I think that one of the key pieces that the `wand.init` method should do is walk the tree and make sure that the spec is valid. Maybe this lives in the main `wand.js` file, maybe it lives in `validate.js` or something like that. This would definitely be one of the things.
