### ISSUE TITLE
How do we know which is the first node to render?

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/wand#21]
We were thinking of writing a test so see what happens if no node with id `0` is designated.

What should happen in this case? What should we test for?

**Comment by bsmithgall** [comment]
Maybe default to the zero-index and have the ability to override that passing some sort of `baseNode` parameter or something like that.

**Comment by ErnieAtLYD** [comment]
I'm okay with that, by the way. That should be written somewhere, that's all. (Note to self to do so)

**Comment by ErnieAtLYD** [comment]
This issue has been resolved:
https://github.com/codeforamerica/wand/blob/master/src/js/wand.js#L24-L25
