### ISSUE TITLE
Grunt test aborts on a fresh install

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/wand#23]
This is on the current master branch.

``` shell
$ grunt test
Running "jshint:files" (jshint) task
>> 2 files lint free.

Running "karma:single" (karma) task
Warning: The api interface has changed. Please use
  server = new Server(config, [done])
  server.start()
instead. Use --force to continue.

Aborted due to warnings.
```

**Comment by mapsam** [comment]
I was getting the same errors, @bengolder and wasn't able to resolve the issue by nuking `node_modules`, updating, and reinstalling. Can't seem to find anything about the error on Google either.

**Comment by bsmithgall** [comment]
http://stackoverflow.com/questions/31445614/warning-the-api-interface-has-changed-when-running-karma-on-grunt

can you try this fix @mapsam @bengolder
