### ISSUE TITLE
Template Rendering

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/wand#5]
We want to provide basic templates for our users to be able to have beautiful UI/UX without having to do any additional work out of the box.

TODO: 
- [x] Research potential templating libraries (client-side templates for now)
- [x] Less/Sass preprocessing work with our taskrunner
- [x] Draw out basic UIs
- [ ] Work on wand render functions to improve functionality

Group members:
@phiden @mapsam @TiffanyAndrews @nikzei

**Comment by mapsam** [comment]
Looking forward to working on these! Some quick ideas that came up while working today:

### Skins

Allow the user to specify a "skin" in the params of the JSON. This would effectively give themes to the layout, either predefined or linking to an external CSS file.

### Layout

This is effectively telling the wizard how to render its information, such as appending the current question to the DOM (`append`) or completely wiping the DOM (`erase`) between each question as the user clicks a trigger.

Here's an example JSON with the updated `skin` and `layout` options.

``` JS
{
  elem: "wizard",
  skin: "red", // or "https://style.codeforamerica.org/2/style/css/main.css"
  layout: "append", // or "erase"
  nodes: []
}
```

**Comment by mapsam** [comment]
Sass preprocessing added by @phiden in #26

**Comment by mapsam** [comment]
Going to hear some words from @phiden today about templating - then we'll work towards a decision!

**Comment by bsmithgall** [comment]
Another option for simple templating is [underscore](http://underscorejs.org/#template), which is attractive because it also gives us a ton of other stuff.

If we aren't taking advantage of the more intensive features of handlebars, it seems like a lot of weight to carry around. Thoughts?

**Comment by phiden** [comment]
Totally open to suggestion. Are there more pros for Underscore?

**Comment by mapsam** [comment]
I'm open to testing out a few options! No reason not to - since we'll come away with more knowledge of each of the libraries.

@phiden I'll take a stab at _underscore and report back.

**Comment by bsmithgall** [comment]
I'd like to close this issue in favor of more meaningful, smaller work items.

Objections @mapsam @phiden ?

**Comment by mapsam** [comment]
:+1:
